set:
  features: false
  train: false
  eval: false
  viz: false

model: "DilatedCNN"

path:
  root_dir:  /content/birdvox_meta
  train_dir: ${path.root_dir}/Development_Set/Training_Set
  eval_dir:  ${path.root_dir}/Development_Set/Validation_Set
  feat_path: ${path.root_dir}/Features
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  model: ${path.root_dir}/models/${model}
  best_model: ${path.model}/best_model.pth
  last_model: ${path.model}/last_model.pth

features:
  seg_len: 0.200
  hop_seg: 0.050
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
train:
  num_classes: 15
  n_shot: 5
  k_way : 10
  device: cuda
  lr_rate: 0.0001
  scheduler_gamma: 0.5
  scheduler_step_size: 10
  epochs: 18

eval:
  samples_neg: 650
  iterations: 3
  query_batch_size: 8
  negative_set_batch_size : 16



